### PR TITLE
add balena (fixes #104)

### LINKED ISSUE #104: balena engine for vagrant box
balena daemon will fail when running on vagrant box due to systemd configuration.

```
systemd[1]: Failed to listen on Docker Socket for the API.
```

### PR DESCRIPTION
**Pull request by phamduchongan93**
- able to download the service over balena repos.
- still unable to write systemd files.

### CODE REVIEW

**Comment by phamduchongan93** [comment]
code to test while you are in terminal.
Require root privillege.

```
systemctl start balena
systemctl status balena
balena ps

```

**Comment by vmnet8** [comment]
I tested on Pi (release-112), before testing systemctl status, also run `systemctl enable balena` first.



```
root@treehouses:~# systemctl enable balena
Created symlink /etc/systemd/system/multi-user.target.wants/balena.service → /etc/systemd/system/balena.service.
root@treehouses:~# systemctl start balena
Job for balena.service failed because a fatal signal was delivered causing the control process to dump core.
See "systemctl status balena.service" and "journalctl -xe" for details.
root@treehouses:~# systemctl status balena
● balena.service - Balena Application Container Engine
   Loaded: loaded (/etc/systemd/system/balena.service; enabled; vendor preset: enabled)
   Active: failed (Result: core-dump) since Fri 2019-11-08 23:58:27 UTC; 10s ago
     Docs: https://www.balena.io/engine/
  Process: 15149 ExecStart=/usr/bin/balena-engine-daemon -H tcp://0.0.0.0:2375 -H unix:///var/run/balena-engine.sock (code=dumped, signal=SEGV
 Main PID: 15149 (code=dumped, signal=SEGV)

Nov 08 23:58:27 treehouses systemd[1]: balena.service: Service RestartSec=100ms expired, scheduling restart.
Nov 08 23:58:27 treehouses systemd[1]: balena.service: Scheduled restart job, restart counter is at 3.
Nov 08 23:58:27 treehouses systemd[1]: Stopped Balena Application Container Engine.
Nov 08 23:58:27 treehouses systemd[1]: balena.service: Start request repeated too quickly.
Nov 08 23:58:27 treehouses systemd[1]: balena.service: Failed with result 'core-dump'.
Nov 08 23:58:27 treehouses systemd[1]: Failed to start Balena Application Container Engine.


Balena is  enabled but failed.

```

**Comment by dogi** [comment]
@vmnet8 2 things:
- look into `treehouses help container`
- please do not write about treehouses/builder problems here

**Comment by dogi** [comment]
> de to test while you are in terminal.
> Require root privillege.
> 
> ```
> systemctl start balena
> systemctl status balena
> balena ps
> ```

@phamduchongan93 did you try `treehouses container balena`

**Comment by phamduchongan93** [comment]
> > de to test while you are in terminal.
> > Require root privillege.
> > ```
> > systemctl start balena
> > systemctl status balena
> > balena ps
> > ```
> 
> @phamduchongan93 did you try `treehouses container balena`

My bad, the command was prompted with system detection error. I have to come up with a way to disable the system checking.

**Comment by vmnet8** [comment]
```
ubuntu@vmnet8:~/git_repo/template$ vagrant ssh
Linux template 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u1 (2019-09-20) x86_64

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
You have new mail.
vagrant@template:~$ sudo -i
 root@template:~# systemctl status balena
● balena.service - Docker Application Container Engine
   Loaded: loaded (/etc/systemd/system/balena.service; disabled; vendor preset: enabled)
   Active: inactive (dead)
     Docs: https://docs.docker.com
root@template:~# systemctl enable balena
Created symlink /etc/systemd/system/multi-user.target.wants/balena.service → /etc/systemd/system/balena.service.
root@template:~# systemctl start balena
root@template:~# systemctl status balena
● balena.service - Docker Application Container Engine
   Loaded: loaded (/etc/systemd/system/balena.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2019-11-11 06:52:42 GMT; 4s ago
     Docs: https://docs.docker.com
 Main PID: 11544 (balena-engine-d)
    Tasks: 23 (limit: 3874)
   Memory: 49.9M
   CGroup: /system.slice/balena.service
           ├─11544 /usr/local/bin/balena-engine-daemon -H unix:///var/run/balena-engine.sock
           └─11551 balena-engine-containerd --config /var/run/balena-engine/containerd/containerd.toml

Nov 11 06:52:40 template balena-engine-daemon[11544]: time="2019-11-11T06:52:40.038592727Z" level=warning msg="Your kernel does not support cg
Nov 11 06:52:40 template balena-engine-daemon[11544]: time="2019-11-11T06:52:40.038630774Z" level=warning msg="Your kernel does not support cg
Nov 11 06:52:40 template balena-engine-daemon[11544]: time="2019-11-11T06:52:40.051593442Z" level=info msg="Loading containers: start."
Nov 11 06:52:41 template balena-engine-daemon[11544]: time="2019-11-11T06:52:41.201062322Z" level=info msg="Default bridge (balena0) is assign
Nov 11 06:52:41 template balena-engine-daemon[11544]: time="2019-11-11T06:52:41.631408256Z" level=info msg="Loading containers: done."
Nov 11 06:52:42 template balena-engine-daemon[11544]: time="2019-11-11T06:52:42.152829737Z" level=warning msg="failed to retrieve balena-engin
Nov 11 06:52:42 template balena-engine-daemon[11544]: time="2019-11-11T06:52:42.153332212Z" level=info msg="Docker daemon" commit=3fdfd0d grap
Nov 11 06:52:42 template balena-engine-daemon[11544]: time="2019-11-11T06:52:42.153738635Z" level=info msg="Daemon has completed initializatio
Nov 11 06:52:42 template systemd[1]: Started Docker Application Container Engine.
Nov 11 06:52:42 template balena-engine-daemon[11544]: time="2019-11-11T06:52:42.192382765Z" level=info msg="API listen on /var/run/balena-engi
root@template:~# balena ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
root@template:~# 
```

**Comment by phamduchongan93** [comment]
It seems like the `treehouses` command doesn't appear when the box is built.

**Pull request merged**
